# -*- coding: utf-8 -*-
"""Corpus dump — the exhaustive layer under a dossier.

Writes _dossiers/_pulls/<slug>.md: EVERY non-RT tweet matching the patterns,
both dbs, chronological, full_text verbatim from the row (zero agent
transcription — reproduction is script work), with media/transcription flags.

Design (2026-07-22, the Princess post-mortem): selection is the failure
surface. The dossier layer keeps judgment only at TRIAGE (is this about the
model?) — the agent lists excluded ids with reasons in the dossier proper;
the pull file itself stays pristine and regenerable. Importance-ranking is
presentation, never a gate; nothing in the cluster goes unrecorded.

Usage:
  python tools/corpus_dump.py claude-sonnet-4-5 "sonnet 4.5,sonnet-4.5,sonnet 4-5,claude-sonnet-4-5,sonnet4.5"

Rerun any time; output is deterministic for a given db state.
"""
import os, re, sys, sqlite3

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN = r'C:\Users\Admin\Downloads\janus-corpus-v2.db'
SUPP = r'C:\Users\Admin\Downloads\janus-corpus-supplement.db'
OUT = os.path.join(REPO, '_dossiers', '_pulls')
os.makedirs(OUT, exist_ok=True)

def norm_date(s):
    s = (s or '').replace('T', ' ').replace('Z', '')
    return s[:16]

def pull(con, pats, db_tag, media_q=None, trans_q=None):
    like = ' OR '.join("lower(full_text) LIKE ?" for _ in pats)
    q = f"""SELECT tweet_id, author_username, created_at, favorite_count, retweet_count, full_text
            FROM tweets WHERE ({like}) AND full_text NOT LIKE 'RT @%'"""
    out = {}
    for tid, author, created, favs, rts, text in con.execute(q, [f'%{p}%' for p in pats]):
        media = []
        if media_q:
            media = con.execute(media_q, (tid,)).fetchall()
        out[tid] = dict(author=author or '—', created=norm_date(created), favs=favs or 0,
                        rts=rts or 0, text=text, media=media, db=db_tag)
    return out

def main():
    if len(sys.argv) < 3:
        print(__doc__); return
    slug = sys.argv[1]
    pats = [p.strip().lower() for p in sys.argv[2].split(',') if p.strip()]

    main_con = sqlite3.connect(MAIN)
    supp_con = sqlite3.connect(SUPP)
    rows = pull(main_con, pats, 'main',
                media_q="SELECT media_url, CASE WHEN transcription IS NOT NULL AND transcription != '' THEN transcription ELSE NULL END FROM media WHERE tweet_id=?")
    for tid, r in pull(supp_con, pats, 'supp',
                       media_q="SELECT media_url, NULL FROM media_supp WHERE tweet_id=?").items():
        if tid not in rows:
            rows[tid] = r

    ordered = sorted(rows.items(), key=lambda kv: kv[1]['created'])
    n_media = sum(1 for _, r in ordered if r['media'])
    n_untr = sum(1 for _, r in ordered if r['media'] and not any(m[1] for m in r['media']))

    path = os.path.join(OUT, slug + '.md')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(f'# corpus pull — {slug}\n\n')
        f.write(f'patterns: {", ".join("`" + p + "`" for p in pats)}\n')
        f.write(f'generated by tools/corpus_dump.py — regenerable, do not hand-edit; '
                f'triage exclusions (with reasons) belong in the dossier proper.\n')
        f.write(f'count: {len(ordered)} unique non-RT tweets · {n_media} with media '
                f'({n_untr} fully untranscribed) · range {ordered[0][1]["created"][:10]} → {ordered[-1][1]["created"][:10]}\n\n---\n\n' if ordered else 'count: 0\n')
        for tid, r in ordered:
            flags = ''
            if r['media']:
                tr = sum(1 for m in r['media'] if m[1])
                flags = f' · media {len(r["media"])} ({tr} transcribed)'
            f.write(f'**{tid}** · @{r["author"]} · {r["created"]} · ♥{r["favs"]} ↻{r["rts"]}{flags} · https://x.com/{r["author"]}/status/{tid}\n\n')
            f.write('```\n' + r['text'].replace('```', 'ˋˋˋ') + '\n```\n\n')
            for url, trans in r['media']:
                if trans:
                    f.write(f'> transcription ({url.rsplit("/",1)[-1]}): {trans}\n\n'.replace('\n> \n', '\n'))
    print(f'{path}: {len(ordered)} tweets, {n_media} with media ({n_untr} untranscribed)')

if __name__ == '__main__':
    main()
